SQL> CREATE TABLE SEMPL(EMPNO NUMBER(3),ENAME VARCHAR2(15),
DOB DATE,SAL NUMBER(7,2),
DEPTNO NUMBER(2));

SQL>DESCRIBE SEMPL;

SQL>ALTER TABLE SEMPL ADD(SAL NUMBER(7,2),DEPTNO NUMBER(2));

SQL>DESCRIBE SEMPL;

SQL>ALTER TABLE SEMPL MODIFY(ENAME VARCHAR2(20));

SQL>DESCRIBE SEMPL;

SQL>ALTER TABLE SEMPL DROP(DEPTNO);

SQL>DESCRIBE SEMPL;

SQL>INSERT INTO SEMPL VALUES(101,’SATISH’,
’14-FEB-78’,5500,10);
SQL>INSERT INTO SEMPL VALUES(102,’SURESH’,
’12-JAN-77’,6500,20);
SQL>INSERT INTO SEMPL VALUES(101,’PRAKASH’,
’14-MAY-78’,7500,10);
SQL>COMMIT;
SQL> SELECT * FROM SEMPL;

SQL>INSERT INTO SEMPL(EMPNO,ENAME,SAL) VALUES(201,’RAVI’ ,3500);
SQL>INSERT INTO SEMPL(EMPNO,ENAME,SAL) VALUES(202,’RAJU’ ,4500);
SQL>INSERT INTO SEMPL(EMPNO,ENAME,SAL) VALUES(203,’KIRAN’ ,8500);
SQL>COMMIT;

SQL>INSERT INTO SEMPL VALUES(&EMPNO,’&ENAME’,’&DOB’,&SAL,
&DEPTNO);
SQL>/ (5TIMES)

SQL>INSERT INTO SEMPL(EMPNO,DOB) VALUES(&EMPNO,’&DOB’);
SQL>/ (5 TIMES)

SQL>SELECT * FROM SEMPL;

SQL>SELECT EMPNO,ENAME FROM SEMPL;

SQL>SELECT * FROM SEMPL WHERE SAL < 5000;

SQL>SELECT * FROM SEMPL WHERE
SAL>5000 AND SAL<8000;

SQL>SELECT * FROM SEMPL
WHERE DOB=’12-FEB-77’;

SQL>SELECT * FROM SEMPL
WHERE EMPNO=101 OR EMPNO=103
OR EMPNO=201;
SQL>SELECT * FROM SEMPL
WHERE EMPNO IN(101,103,201);

SQL>SELECT * FROM SEMPL
WHERE SAL>5000 AND DOB=’12-JAN-78’;

SQL>SELECT EMPNO,ENAME, SAL,SAL*12
FROM SEMPL;
SQL>SELECT EMPNO,ENAME, SAL,SAL*12 ASAL
FROM SEMPL;

SQL>SELECT * FROM SEMPL
WHERE ENAME LIKE ‘S%’;

SQL>SELECT * FROM SEMPL
WHERE ENAME LIKE ‘%H’;

SQL>SELECT * FROM SEMPL
WHERE ENAME LIKE ‘R%U’;

SQL>SELECT * FROM SEMPL
WHERE SAL IS NULL;

SQL>SELECT * FROM SEMPL
WHERE ENAME LIKE ‘S%’ AND SAL>6000;

SQL>SELECT * FROM SEMPL
WHERE ENAME LIKE’R_ _ _’;

SQL>SELECT * FROM SEMPL
WHERE SAL>=5000 AND SAL<=8000;
(OR)
SQL>SELECT * FROM SEMPL
WHERE SAL BETWEEN 5000 AND 8000;
